# Site settings
# in the templates available like {{ site.myvariable }}.
title: SoraPainting 
email: sorapaintinginfo@gmail.com
brand: SoraPainting
headline: Leave the difficult project to us You definitely come back to us
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sorapainting.github.io" # the base hostname & protocol for your site
copyright: 2017 SoraPainting Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 336992

# Contacts
email: sorapaintinginfo@gmail.com 
phone: +61 420 770 163

# Tracking
#googleAnalitycsID: UA-83933844-1

